stages:
- deploy

cache:
  paths:
  - node_modules

# 佈署
發佈正式機:
  stage: deploy
  only:
  - master

  script:
  - npm i
  - npm run build
  - ln -sfn "`pwd`/dist" /var/www/html/traveltourbobo
  - cd ~/servers/
  - ansible-playbook sync/traveltourbobo.yaml